### ISSUE TITLE
please do not leak JIRA credentials :)

### ISSUE THREAD

**Issue by haloz** [janpetzold/magic-estimation#1]
hello Jan,
I don't think it is wise to include the credentials to your JIRA instance in this public repository (default.json).

best regards
Sebastian

**Comment by janpetzold** [comment]
Absolutely - thanks!

**Comment by MoriTanosuke** [comment]
You might want to read https://help.github.com/articles/removing-sensitive-data-from-a-repository/ and remove the credentials from your repositories history too. I can still open the commit 234dcf57dbba2a453fb2ecbeb246d2ae034f9a1c and the credentials are still valid to log in.
