### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by Zawenn** [janpetzold/magic-estimation#1]
Can you help me? I get the following error:

It would be great, if I could use the tool.

thanks
Sven
-----
Magic estimation server app listening on port 3000
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/Users/user/Downloads/magic-estimation-master/backend/jira.js:21:31)
    at self.callback (/Users/user/Downloads/magic-estimation-master/node_modules/request/request.js:200:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.onRequestError (/Users/user/Downloads/magic-estimation-master/node_modules/request/request.js:831:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)

Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! magic-estimation@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the magic-estimation@1.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the magic-estimation package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs magic-estimation
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls magic-estimation
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/.npm/_logs/2017-05-18T12_08_24_762Z-debug.log

**Comment by janpetzold** [comment]
Hi,quite likely the JIRA API response is not usable. Check the URL call manually:

https://USERNAME:PASSWORD@HOST/rest/agile/latest/board/BOARD_ID/sprint?state=active,future'

Also the user you're using for JIRA authentication needs to have appropriate permission.

**Comment by Zawenn** [comment]
Thank you for your quick response - it was a specialcharacter in my password.

I've created a testuser and it works!

Great place to start digital magic estimation! Will you improve the tool in the furure? Like "send estimation to JIRA"? :)

________________________________
Von: Jan Petzold <notifications@github.com>
Gesendet: Donnerstag, 18. Mai 2017 21:10:30
An: janpetzold/magic-estimation
Cc: Sven Hary; Author
Betreff: Re: [janpetzold/magic-estimation] It does not work (#1)


Hi,quite likely the JIRA API response is not usable. Check the URL call manually:

https://USERNAME:PASSWORD@HOST/rest/agile/latest/board/BOARD_ID/sprint?state=active,future'

Also the user you're using for JIRA authentication needs to have appropriate permission.

**Comment by janpetzold** [comment]
Yes, there are several things to improve, the point you've mentioned is one of them. I use the tool now on a bi-weekly basis and it pretty much does the job though. But I'm happily accepting PRs :)
